# Generated by Django 4.2.11 on 2024-06-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_event_options_alter_event_status'),
        ('store', '0002_cartorder_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='booking.event'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
