# Generated by Django 4.2.11 on 2025-01-11 19:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_people', models.IntegerField(default=30)),
                ('price', models.FloatField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('hours', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('n_people',),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desciption', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(blank=True, choices=[('Bootstrap Icons', 'Bootstrap Icons'), ('Fontawesome Icons', 'Fontawesome Icons'), ('Box Icons', 'Box Icons'), ('Remi Icons', 'Remi Icons'), ('Flat Icons', 'Flat Icons')], max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date', models.DateField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival', models.TimeField(default=datetime.time(10, 0))),
                ('departure', models.TimeField(default=datetime.time(0, 0))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('advance', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('solicitud', 'Solicitud de Reserva'), ('aceptacion', 'Aceptación de Reserva'), ('apartado', 'Apartado inicial'), ('liquidado', 'Monto liquidado'), ('liquidado_entregado', 'Monto liquidado y lugar entregado'), ('entregado', 'Entregado'), ('finalizado', 'Reserva finalizada'), ('cancelado', 'Reserva cancelada'), ('rechazado', 'Rechazado')], default='solicitud', max_length=100)),
                ('rating', models.PositiveIntegerField(blank=True, default=0)),
                ('rating_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('payment_intent', models.CharField(blank=True, max_length=1000, null=True)),
                ('eid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12345', length=10, max_length=10, prefix='')),
                ('description', models.TextField(default='')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('extras', models.ManyToManyField(blank=True, to='booking.extra')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package', to='booking.package')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue', to='booking.venue')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
