# Generated by Django 5.0.1 on 2024-04-25 18:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_people', models.IntegerField(default=30)),
                ('price', models.FloatField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('hours', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date', models.DateField(unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival', models.TimeField(default=datetime.time(10, 0))),
                ('departure', models.TimeField(default=datetime.time(0, 0))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('advance', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('en_revision', 'En revisión'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='en_revision', max_length=100)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('rating_comment', models.CharField(max_length=255, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('extras', models.ManyToManyField(to='booking.extra')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package', to='booking.package')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue', to='booking.venue')),
            ],
        ),
    ]
