# Generated by Django 5.0.1 on 2024-04-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desciption', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('n_people',)},
        ),
    ]
