# Generated by Django 4.2.11 on 2025-02-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
