# Generated by Django 4.2.11 on 2024-05-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rule_alter_package_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
