# Generated by Django 4.2.11 on 2024-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_package_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(default=models.CharField(blank=True, max_length=255), unique=True),
        ),
    ]
