# Generated by Django 4.2.11 on 2024-06-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_event_payment_intent_venuefeatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='extras',
            field=models.ManyToManyField(null=True, to='booking.extra'),
        ),
    ]
