# Generated by Django 4.2.11 on 2024-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_event_options_alter_event_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extras',
            field=models.ManyToManyField(blank=True, null=True, to='booking.extra'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
