# Generated by Django 4.2.11 on 2024-06-28 18:32

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12345', length=10, max_length=10, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
