# Generated by Django 4.2.11 on 2024-06-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_event_eid_alter_event_id'),
    ]

    operations = [
    ]
