# Generated by Django 4.2.11 on 2024-06-28 18:33

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20240628_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12345', length=10, max_length=10, null=True, prefix='', unique=True),
        ),
    ]
