# Generated by Django 4.2.11 on 2024-07-27 00:20

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_venue_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='eid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12345', length=10, max_length=10, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
